version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run:
          name: Set up
          command: |
                    sudo gem install bundler
                    sudo bundle update && bundle install
                    ruby -v && bundler -v && bundle exec jekyll -v
      # Store bundle cache
      - save_cache:
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Tests
          command: |
                    sudo rake test
