version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout
      - run:
          name: Preparing project
          command: |
                    sudo gem install bundler
                    sudo gem install jekyll
      - run:
          name: Run Test
          command: |
                    rake test