version: 2.1
jobs:
  build:
    working_directory: ~/tmp

    docker:
      - image: circleci/ruby:2.6.3

    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        keys:
          - v1-dependencies-bundler-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-bundler-

      - run:
          name: Set up
          command: |
                    sudo gem install bundler
                    sudo bundle update && bundle install
                    ruby -v && bundler -v && bundle exec jekyll -v

      # Store bundle cache
      - type: cache-save
        key: v1-dependencies-bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

            sudo gem install bundler
            sudo bundle update && bundle install
            ruby -v && bundler -v && bundle exec jekyll -v
      - run:
          name: Tests
          command: |
            sudo rake test
